### ISSUE TITLE
Wildfly/Tomcat won't start if zorka can't resolve zabbix active server name

### ISSUE THREAD

**Issue by kkmaslowski** [jitlogic/zorka#180]
Steps to reproduce: 

1. Enable active checks in zorka.properties and set non existent hostname as server
zabbix.active = yes
zabbix.active.server.addr = zabbix-server:10051
2. Restart Wildfly or Tomcat instance

Log from Wildfly:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NullPointerException
        at java.net.Socket.<init>(Socket.java:428)
        at java.net.Socket.<init>(Socket.java:244)
        at com.jitlogic.zorka.core.integ.zabbix.ZabbixActiveAgent.start(ZabbixActiveAgent.java:165)
        at com.jitlogic.zorka.core.AgentInstance.initBshLibs(AgentInstance.java:205)
        at com.jitlogic.zorka.core.AgentInstance.start(AgentInstance.java:179)
        at com.jitlogic.zorka.agent.AgentMain.premain(AgentMain.java:101)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
*** JBossAS process (5016) received ABRT signal ***

```

**Comment by jitlogic** [comment]
Fixed in 1.0.16. Zabbix connection was starting synchronously with agent initialization, now it starts in its own thread.
